-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

CREATE TABLE customer (
    id_customer    INTEGER NOT NULL,
    customer_name  VARCHAR2(128 BYTE) NOT NULL
);

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( id_customer );



CREATE TABLE game (
    game_name  VARCHAR2(128 BYTE) NOT NULL,
    year       INTEGER NOT NULL
);

ALTER TABLE game ADD CONSTRAINT game_pk PRIMARY KEY ( game_name,year );


CREATE TABLE game_genre (
    game_name   VARCHAR2(128 BYTE) NOT NULL,
    year        INTEGER NOT NULL,
    genre_name  VARCHAR2(30) NOT NULL
);

ALTER TABLE game_genre ADD CONSTRAINT game_genre_pk PRIMARY KEY ( game_name,year );


CREATE TABLE game_publisher (
    game_name       VARCHAR2(128 BYTE) NOT NULL,
    year            INTEGER NOT NULL,
    publisher_name  VARCHAR2(128 BYTE) NOT NULL
);

ALTER TABLE game_publisher ADD CONSTRAINT game_publisher_pk PRIMARY KEY ( game_name,year );


CREATE TABLE genre (
    genre_name VARCHAR2(30 BYTE) NOT NULL
);

ALTER TABLE genre ADD CONSTRAINT genre_pk PRIMARY KEY ( genre_name );


CREATE TABLE publisher (
    publisher_name VARCHAR2(128 BYTE) NOT NULL
);

ALTER TABLE publisher ADD CONSTRAINT publisher_pk PRIMARY KEY ( publisher_name );


CREATE TABLE region (
    region_name VARCHAR2(30 BYTE) NOT NULL
);

ALTER TABLE region ADD CONSTRAINT region_pk PRIMARY KEY ( region_name );


CREATE TABLE sales_customer (
    id_customer       INTEGER NOT NULL,
    customer_name     VARCHAR2(120 BYTE),
    game_name         VARCHAR2(128 BYTE) NOT NULL,
    year              INTEGER NOT NULL,
    price             NUMBER(10, 2),
    discount          NUMBER(5, 2),
    discounted_price  NUMBER(10, 2)
);

ALTER TABLE sales_customer
    ADD CONSTRAINT sales_customer_pk PRIMARY KEY ( id_customer, game_name,year );


CREATE TABLE sales_region (
    game_name    VARCHAR2(128 BYTE) NOT NULL,
    year         INTEGER NOT NULL,
    region_name  VARCHAR2(30 BYTE) NOT NULL,
    sales        NUMBER(10, 2)
);

ALTER TABLE sales_region ADD CONSTRAINT sales_region_pk PRIMARY KEY ( game_name,year,region_name);


ALTER TABLE game_genre
    ADD CONSTRAINT game_genre_game_fk FOREIGN KEY ( game_name,
                                                    year )
        REFERENCES game ( game_name,
                          year );

ALTER TABLE game_genre
    ADD CONSTRAINT game_genre_genre_fk FOREIGN KEY ( genre_name )
        REFERENCES genre ( genre_name );

ALTER TABLE game_publisher
    ADD CONSTRAINT game_publisher_game_fk FOREIGN KEY ( game_name,
                                                        year )
        REFERENCES game ( game_name,
                          year );

ALTER TABLE game_publisher
    ADD CONSTRAINT game_publisher_publisher_fk FOREIGN KEY ( publisher_name )
        REFERENCES publisher ( publisher_name );

ALTER TABLE sales_customer
    ADD CONSTRAINT sales_customer_customer_fk FOREIGN KEY ( id_customer )
        REFERENCES customer ( id_customer );

ALTER TABLE sales_customer
    ADD CONSTRAINT sales_customer_game_fk FOREIGN KEY ( game_name,
                                                        year )
        REFERENCES game ( game_name,
                          year );

ALTER TABLE sales_region
    ADD CONSTRAINT sales_region_game_fk FOREIGN KEY ( game_name,
                                                      year )
        REFERENCES game ( game_name,
                          year );

ALTER TABLE sales_region
    ADD CONSTRAINT sales_region_region_fk FOREIGN KEY ( region_name )
        REFERENCES region ( region_name );

